// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/pkg/spn/spn.proto

package spn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetriNet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matrix        []int32                `protobuf:"varint,1,rep,packed,name=matrix,proto3" json:"matrix,omitempty"`
	Places        int32                  `protobuf:"varint,2,opt,name=places,proto3" json:"places,omitempty"`
	Transitions   int32                  `protobuf:"varint,3,opt,name=transitions,proto3" json:"transitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetriNet) Reset() {
	*x = PetriNet{}
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetriNet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetriNet) ProtoMessage() {}

func (x *PetriNet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetriNet.ProtoReflect.Descriptor instead.
func (*PetriNet) Descriptor() ([]byte, []int) {
	return file_internal_pkg_spn_spn_proto_rawDescGZIP(), []int{0}
}

func (x *PetriNet) GetMatrix() []int32 {
	if x != nil {
		return x.Matrix
	}
	return nil
}

func (x *PetriNet) GetPlaces() int32 {
	if x != nil {
		return x.Places
	}
	return 0
}

func (x *PetriNet) GetTransitions() int32 {
	if x != nil {
		return x.Transitions
	}
	return 0
}

type ReachabilityGraph struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Vertices       []*Vertex              `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
	Edges          []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	ArcTransitions []int32                `protobuf:"varint,3,rep,packed,name=arc_transitions,json=arcTransitions,proto3" json:"arc_transitions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReachabilityGraph) Reset() {
	*x = ReachabilityGraph{}
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReachabilityGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReachabilityGraph) ProtoMessage() {}

func (x *ReachabilityGraph) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReachabilityGraph.ProtoReflect.Descriptor instead.
func (*ReachabilityGraph) Descriptor() ([]byte, []int) {
	return file_internal_pkg_spn_spn_proto_rawDescGZIP(), []int{1}
}

func (x *ReachabilityGraph) GetVertices() []*Vertex {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *ReachabilityGraph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ReachabilityGraph) GetArcTransitions() []int32 {
	if x != nil {
		return x.ArcTransitions
	}
	return nil
}

type Vertex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Marking       []int32                `protobuf:"varint,1,rep,packed,name=marking,proto3" json:"marking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_internal_pkg_spn_spn_proto_rawDescGZIP(), []int{2}
}

func (x *Vertex) GetMarking() []int32 {
	if x != nil {
		return x.Marking
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           int32                  `protobuf:"varint,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest          int32                  `protobuf:"varint,2,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_internal_pkg_spn_spn_proto_rawDescGZIP(), []int{3}
}

func (x *Edge) GetSrc() int32 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *Edge) GetDest() int32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

type SPNData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PetriNet          *PetriNet              `protobuf:"bytes,1,opt,name=petri_net,json=petriNet,proto3" json:"petri_net,omitempty"`
	ReachabilityGraph *ReachabilityGraph     `protobuf:"bytes,2,opt,name=reachability_graph,json=reachabilityGraph,proto3" json:"reachability_graph,omitempty"`
	LambdaValues      []float64              `protobuf:"fixed64,3,rep,packed,name=lambda_values,json=lambdaValues,proto3" json:"lambda_values,omitempty"`
	SteadyStateProbs  []float64              `protobuf:"fixed64,4,rep,packed,name=steady_state_probs,json=steadyStateProbs,proto3" json:"steady_state_probs,omitempty"`
	AverageMarkings   []float64              `protobuf:"fixed64,5,rep,packed,name=average_markings,json=averageMarkings,proto3" json:"average_markings,omitempty"`
	MarkingDensities  []*MarkingDensity      `protobuf:"bytes,6,rep,name=marking_densities,json=markingDensities,proto3" json:"marking_densities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SPNData) Reset() {
	*x = SPNData{}
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPNData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPNData) ProtoMessage() {}

func (x *SPNData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPNData.ProtoReflect.Descriptor instead.
func (*SPNData) Descriptor() ([]byte, []int) {
	return file_internal_pkg_spn_spn_proto_rawDescGZIP(), []int{4}
}

func (x *SPNData) GetPetriNet() *PetriNet {
	if x != nil {
		return x.PetriNet
	}
	return nil
}

func (x *SPNData) GetReachabilityGraph() *ReachabilityGraph {
	if x != nil {
		return x.ReachabilityGraph
	}
	return nil
}

func (x *SPNData) GetLambdaValues() []float64 {
	if x != nil {
		return x.LambdaValues
	}
	return nil
}

func (x *SPNData) GetSteadyStateProbs() []float64 {
	if x != nil {
		return x.SteadyStateProbs
	}
	return nil
}

func (x *SPNData) GetAverageMarkings() []float64 {
	if x != nil {
		return x.AverageMarkings
	}
	return nil
}

func (x *SPNData) GetMarkingDensities() []*MarkingDensity {
	if x != nil {
		return x.MarkingDensities
	}
	return nil
}

type MarkingDensity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Densities     []float64              `protobuf:"fixed64,1,rep,packed,name=densities,proto3" json:"densities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkingDensity) Reset() {
	*x = MarkingDensity{}
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkingDensity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkingDensity) ProtoMessage() {}

func (x *MarkingDensity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_spn_spn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkingDensity.ProtoReflect.Descriptor instead.
func (*MarkingDensity) Descriptor() ([]byte, []int) {
	return file_internal_pkg_spn_spn_proto_rawDescGZIP(), []int{5}
}

func (x *MarkingDensity) GetDensities() []float64 {
	if x != nil {
		return x.Densities
	}
	return nil
}

var File_internal_pkg_spn_spn_proto protoreflect.FileDescriptor

const file_internal_pkg_spn_spn_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/pkg/spn/spn.proto\x12\x03spn\"\\\n" +
	"\bPetriNet\x12\x16\n" +
	"\x06matrix\x18\x01 \x03(\x05R\x06matrix\x12\x16\n" +
	"\x06places\x18\x02 \x01(\x05R\x06places\x12 \n" +
	"\vtransitions\x18\x03 \x01(\x05R\vtransitions\"\x86\x01\n" +
	"\x11ReachabilityGraph\x12'\n" +
	"\bvertices\x18\x01 \x03(\v2\v.spn.VertexR\bvertices\x12\x1f\n" +
	"\x05edges\x18\x02 \x03(\v2\t.spn.EdgeR\x05edges\x12'\n" +
	"\x0farc_transitions\x18\x03 \x03(\x05R\x0earcTransitions\"\"\n" +
	"\x06Vertex\x12\x18\n" +
	"\amarking\x18\x01 \x03(\x05R\amarking\",\n" +
	"\x04Edge\x12\x10\n" +
	"\x03src\x18\x01 \x01(\x05R\x03src\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\x05R\x04dest\"\xbc\x02\n" +
	"\aSPNData\x12*\n" +
	"\tpetri_net\x18\x01 \x01(\v2\r.spn.PetriNetR\bpetriNet\x12E\n" +
	"\x12reachability_graph\x18\x02 \x01(\v2\x16.spn.ReachabilityGraphR\x11reachabilityGraph\x12#\n" +
	"\rlambda_values\x18\x03 \x03(\x01R\flambdaValues\x12,\n" +
	"\x12steady_state_probs\x18\x04 \x03(\x01R\x10steadyStateProbs\x12)\n" +
	"\x10average_markings\x18\x05 \x03(\x01R\x0faverageMarkings\x12@\n" +
	"\x11marking_densities\x18\x06 \x03(\v2\x13.spn.MarkingDensityR\x10markingDensities\".\n" +
	"\x0eMarkingDensity\x12\x1c\n" +
	"\tdensities\x18\x01 \x03(\x01R\tdensitiesB#Z!spn-benchmark-ds/internal/pkg/spnb\x06proto3"

var (
	file_internal_pkg_spn_spn_proto_rawDescOnce sync.Once
	file_internal_pkg_spn_spn_proto_rawDescData []byte
)

func file_internal_pkg_spn_spn_proto_rawDescGZIP() []byte {
	file_internal_pkg_spn_spn_proto_rawDescOnce.Do(func() {
		file_internal_pkg_spn_spn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_spn_spn_proto_rawDesc), len(file_internal_pkg_spn_spn_proto_rawDesc)))
	})
	return file_internal_pkg_spn_spn_proto_rawDescData
}

var file_internal_pkg_spn_spn_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_pkg_spn_spn_proto_goTypes = []any{
	(*PetriNet)(nil),          // 0: spn.PetriNet
	(*ReachabilityGraph)(nil), // 1: spn.ReachabilityGraph
	(*Vertex)(nil),            // 2: spn.Vertex
	(*Edge)(nil),              // 3: spn.Edge
	(*SPNData)(nil),           // 4: spn.SPNData
	(*MarkingDensity)(nil),    // 5: spn.MarkingDensity
}
var file_internal_pkg_spn_spn_proto_depIdxs = []int32{
	2, // 0: spn.ReachabilityGraph.vertices:type_name -> spn.Vertex
	3, // 1: spn.ReachabilityGraph.edges:type_name -> spn.Edge
	0, // 2: spn.SPNData.petri_net:type_name -> spn.PetriNet
	1, // 3: spn.SPNData.reachability_graph:type_name -> spn.ReachabilityGraph
	5, // 4: spn.SPNData.marking_densities:type_name -> spn.MarkingDensity
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_pkg_spn_spn_proto_init() }
func file_internal_pkg_spn_spn_proto_init() {
	if File_internal_pkg_spn_spn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_spn_spn_proto_rawDesc), len(file_internal_pkg_spn_spn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pkg_spn_spn_proto_goTypes,
		DependencyIndexes: file_internal_pkg_spn_spn_proto_depIdxs,
		MessageInfos:      file_internal_pkg_spn_spn_proto_msgTypes,
	}.Build()
	File_internal_pkg_spn_spn_proto = out.File
	file_internal_pkg_spn_spn_proto_goTypes = nil
	file_internal_pkg_spn_spn_proto_depIdxs = nil
}
